---
title: "DMC Explore"
author: "Jackson Cown"
date: '2022-05-17'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# Data Path Init
items.path <- "../data/items.csv"
category_hierarchy.path <- "../data/category_hierarchy.csv"
orders.path <- "../data/orders.csv"

# Load Data sets
items <- read.csv(items.path, sep="|")
category_hierarchy <- read.csv(category_hierarchy.path, sep="|")
orders <- read.csv(orders.path, sep="|")
```


```{r}
head(items)
head(category_hierarchy)
head(orders)
```

### Created new date_orders.csv for visualization in Python with Pandas

- See .ipynb file for implementation.

```{r}
date_order.path <- "../data/date_orders.csv"
date_order <- read.csv(date_order.path)
barplot(num_orders ~ X, date_order,
        ylab="# of Orders",
        xlab="# of Days Since 2020-06-01",
        main="Number of Orders Vs. Number of Days Since 2020-06-01")
```

```{r}
bp <- barplot(num_orders ~ date, date_order,
        ylab="# of Orders",
        xlab="Date of Orders",
        main="Number of Orders Vs. Time")
```

### Visualizing Monthly Trends

```{r}
month_order.path <- "../data/month_orders.csv"
month_order <- read.csv(month_order.path)
month_order$month <- factor(month_order$month, levels=month_order$month)
head(month_order)
```


```{r}
library(ggplot2)
library(RColorBrewer)
colors <- brewer.pal(8, "RdBu") 

g <- ggplot(month_order, aes(x=month, y=num_orders)) + geom_bar(stat="identity", fill=colors)

g + ggtitle("Total # of Orders per Month") + labs(y="# of Orders", x="Month")
```

```{r}
item_orders.path <- "../data/item_orders.csv"
item_orders <- read.csv(item_orders.path)
# g <- ggplot(item_orders, aes(x=itemID, y=num_orders)) + geom_bar(stat="identity")
#g + ggtitle("Total # of Orders per Month") + labs(y="# of Orders", x="Month")
barplot(num_orders ~ itemID, item_orders,
        xlab="Item ID",
        ylab="Number of Orders",
        main="Number of Orders per ItemID  (2020-06-01 to 2021-1-31)")
```

```{r}
colors <- brewer.pal(10, "Paired") 
item_orders_nlargest.path <- "../data/item_orders_nlargest.csv"
item_orders_nlargest <- read.csv(item_orders_nlargest.path)
barplot(num_orders ~ itemID, data=item_orders_nlargest,
        xlab="Item ID",
        ylab="Number of Orders",
        main="Number of Orders Per Item ID of Top 10 Most Sold Items",
        cex.names=0.8,
        col=colors)

```

```{r}
user_orders.path <- "../data/user_orders.csv"
user_orders <- read.csv(user_orders.path)
```

```{r}
user_orders.mean <- mean(user_orders$num_orders)

barplot(num_orders ~ userID, user_orders,
        xlab="User ID",
        ylab="# of Orders",
        main="Number of Orders per UserID (2020-06-01 to 2021-1-31)")
legend(x = "topright",
       legend = "Mean # of Orders",
       lty = 5,
       lwd=2,
       col="red",
       cex=0.65)
abline(h=user_orders.mean, col="red", lty=5, lwd=2)
```

```{r}
colors <- brewer.pal(10, "Paired") 
user_orders_nlargest.path <- "../data/user_orders_nlargest.csv"
user_orders_nlargest <- read.csv(user_orders_nlargest.path)
barplot(num_orders ~ userID, data=user_orders_nlargest,
        xlab="User ID",
        ylab="Number of Orders",
        main="Number of Orders Per User ID of Top 10 Purchasing Users",
        cex.names=0.8,
        col=colors)

```















































